FULL_RANGE = 255
COMMON_RANGE = 20
MAX_DOTS = 10

IP_HEADER_FORMAT = "!BBHHHBBHII"
ICMP_HEADER_FORMAT = "!BBHHH"
ICMP_TIME_FORMAT = "!d"
ICMP_DEFAULT_CODE = 0  # the code for ECHO_REPLY and ECHO_REQUEST

ECHO_REPLY = 0
ECHO_REQUEST = 8
TIME_EXCEEDED = 11
